# -*- coding: utf-8 -*-
"""Cubo_Mask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bU0MGj7324h3FWsZdDXEa1jgyIdJ0Z0E
"""



import cv2
import matplotlib.pyplot as plt 
import numpy as np

def load_image(path_image):
    img = cv2.imread("/content/20221013_093252.jpg")
    return img[...,::-1] 

img =  cv2.imread("/content/20221013_093252.jpg")

#Rojo
redBajo1 = np.array([0, 100, 20], np.uint8)
redAlto1 = np.array([7, 255, 255], np.uint8)
redBajo2=np.array([160, 100, 20], np.uint8)
redAlto2=np.array([180, 255, 255], np.uint8)
#Naranja
orangeBajo1 = np.array([7.5, 100, 20], np.uint8)
orangeAlto1 = np.array([20, 255, 255], np.uint8)

#amarillo
yellowBajo1 = np.array([20, 100, 20], np.uint8)
yellowAlto1 = np.array([36, 255, 255], np.uint8)

#Blanco
whiteBajo1 = np.array([0, 0, 100], np.uint8)
whiteAlto1 = np.array([255, 20, 255], np.uint8)


frameHSV = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

maskRed1 = cv2.inRange(frameHSV, redBajo1, redAlto1)
maskRed2 = cv2.inRange(frameHSV, redBajo2, redAlto2)
maskRed = cv2.add(maskRed1, maskRed2)
maskRedvis = cv2.bitwise_and(load_image(img),load_image(img),mask=maskRed)

maskorange = cv2.inRange(frameHSV, orangeBajo1,orangeAlto1)
maskorangevis = cv2.bitwise_and(load_image(img),load_image(img),mask=maskorange)

maskyellow = cv2.inRange(frameHSV, yellowBajo1,yellowAlto1)
maskyellowvis = cv2.bitwise_and(load_image(img),load_image(img),mask=maskyellow)

maskwhite = cv2.inRange(frameHSV,whiteBajo1,whiteAlto1)
maskwhitevis = cv2.bitwise_and(load_image(img),load_image(img),mask=maskwhite)

fig, axs = plt.subplots(1,5,figsize=(20,5))
axs[0].imshow(load_image(img))
axs[1].imshow(maskRedvis )
axs[1].set_title('Rojo')
axs[2].imshow(maskorangevis)
axs[2].set_title('Naranja')
axs[3].imshow(maskyellowvis)
axs[3].set_title('Amarillo')
axs[4].imshow(maskwhitevis)
axs[4].set_title('Blanco')

img2 =  cv2.imread("/content/20221013_093300.jpg")
def load_image(path_image):
    img = cv2.imread("/content/20221013_093300.jpg")
    return img[...,::-1] 
#Azul
blueBajo1 = np.array([90, 100, 20], np.uint8)
blueAlto1 = np.array([130, 255, 255], np.uint8)

#verde
greenBajo1 = np.array([45, 100, 20], np.uint8)
greenAlto1 = np.array([80, 255, 255], np.uint8)

#Amarillo 
yellowBajo1 = np.array([20, 100, 20], np.uint8)
yellowAlto1 = np.array([36, 255, 255], np.uint8)

frameHSV = cv2.cvtColor(img2,cv2.COLOR_BGR2HSV)

maskblue = cv2.inRange(frameHSV,blueBajo1,blueAlto1)
maskbluevis = cv2.bitwise_and(load_image(img2),load_image(img2),mask=maskblue)

maskgreen = cv2.inRange(frameHSV,greenBajo1,greenAlto1)
maskgreenvis = cv2.bitwise_and(load_image(img2),load_image(img2),mask=maskgreen)

maskyellow = cv2.inRange(frameHSV, yellowBajo1,yellowAlto1)
maskyellowvis = cv2.bitwise_and(load_image(img2),load_image(img2),mask=maskyellow)

maskRed1 = cv2.inRange(frameHSV, redBajo1, redAlto1)
maskRed2 = cv2.inRange(frameHSV, redBajo2, redAlto2)
maskRed = cv2.add(maskRed1, maskRed2)
maskRedvis = cv2.bitwise_and(load_image(img2),load_image(img2),mask=maskRed)

maskwhite = cv2.inRange(frameHSV,whiteBajo1,whiteAlto1)
maskwhitevis = cv2.bitwise_and(load_image(img2),load_image(img2),mask=maskwhite)

fig, axs = plt.subplots(1,6,figsize=(20,5))
axs[0].imshow(load_image(img2))
axs[1].imshow(maskbluevis )
axs[1].set_title('Azul')
axs[2].imshow(maskgreenvis )
axs[2].set_title('verde')
axs[3].imshow(maskyellowvis )
axs[3].set_title('Amarillo')
axs[4].imshow(maskRedvis )
axs[4].set_title('Rojo')
axs[5].imshow(maskwhitevis)
axs[5].set_title('Blanco')

img3 =  cv2.imread("/content/20221013_093306.jpg")
def load_image(path_image):
    img3 = cv2.imread("/content/20221013_093306.jpg")
    return img3[...,::-1] 

whiteBajo1 = np.array([0, 0, 100], np.uint8)
whiteAlto1 = np.array([255, 25, 255], np.uint8)

frameHSV = cv2.cvtColor(img3,cv2.COLOR_BGR2HSV)

maskRed1 = cv2.inRange(frameHSV, redBajo1, redAlto1)
maskRed2 = cv2.inRange(frameHSV, redBajo2, redAlto2)
maskRed = cv2.add(maskRed1, maskRed2)
maskRedvis = cv2.bitwise_and(load_image(img3),load_image(img3),mask=maskRed)

maskorange = cv2.inRange(frameHSV, orangeBajo1,orangeAlto1)
maskorangevis = cv2.bitwise_and(load_image(img3),load_image(img3),mask=maskorange)

maskyellow = cv2.inRange(frameHSV, yellowBajo1,yellowAlto1)
maskyellowvis = cv2.bitwise_and(load_image(img3),load_image(img3),mask=maskyellow)

maskblue = cv2.inRange(frameHSV,blueBajo1,blueAlto1)
maskbluevis = cv2.bitwise_and(load_image(img3),load_image(img3),mask=maskblue)

maskwhite = cv2.inRange(frameHSV,whiteBajo1,whiteAlto1)
maskwhitevis = cv2.bitwise_and(load_image(img3),load_image(img3),mask=maskwhite)

fig, axs = plt.subplots(1,6,figsize=(20,5))
axs[0].imshow(load_image(img3))
axs[1].imshow(maskRedvis )
axs[1].set_title('Rojo')
axs[2].imshow(maskorangevis )
axs[2].set_title('Naranja')
axs[3].imshow(maskyellowvis )
axs[3].set_title('Amarillo')
axs[4].imshow(maskbluevis )
axs[4].set_title('Azul')
axs[5].imshow(maskwhitevis )
axs[5].set_title('Blanco')